tspycher_thirtieth_birthday:
    resource: "@TspycherThirtiethBirthdayBundle/Controller/"
    type:     annotation
    prefix:   /

api_gifts:
    resource: '\Tspycher\Bundle\ThirtiethBirthdayBundle\ApiController\GiftsController'
    type:     rest
    prefix:   /api/

api_participants:
    resource: '\Tspycher\Bundle\ThirtiethBirthdayBundle\ApiController\ParticipantsController'
    type:     rest
    prefix:   /api/

static_gift1:
    path: /static/gift1
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'TspycherThirtiethBirthdayBundle:Static:gift1.html.twig'
